config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'
  resources :portfolios do
    put :sort, on: :collection
  end
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about',   to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'

  mount ActionCable.server => '/cable'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: [:slugged]
  has_many :comments, dependent: :destroy


  validates :title, :body, presence: true
  belongs_to :topic
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  layout 'blog'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :edit, :update, :toggle_status]}, site_admin: :all
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page] || 1).per(5)
    @page_title = 'My portfolio blog'
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comments = @blog.comments
    @comment = Comment.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog = Blog.friendly.find(params[:id])
    @blog.published? ? @blog.draft! : @blog.published!
    redirect_to blogs_path, notice: 'Post status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">

  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog)%> /
      <%= link_to 'Edit', edit_blog_path(blog) %> /
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

  <p><%= blog.body %></p>
</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |message| %>
      <%= js add_gritter(message, title: "Portfolio", sticky: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:'form-control', rows: 20 %>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= paginate @blogs %>
  <%= render @blogs %>
  <%= paginate @blogs %>

</div><!-- /.blog-main -->

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <h2><%= @blog.title %></h2>
  <%= link_to 'Edit', edit_blog_path(@blog) %>
  <p><%= @blog.body %></p>

  <% unless current_user.is_a? GuestUser %>
    <%= form_for @comment, url: '#' do |f| %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit 'Post Comment', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @comments %>
  </div>
</div><!-- /.blog-main -->