config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'
  resources :portfolios do
    put :sort, on: :collection
  end
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about',   to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'

  mount ActionCable.server => '/cable'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                               reject_if: ->(attrs){ attrs['name'].blank? }
  include Placeholder
  validates :title, :body,  presence: true

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image,  PortfolioUploader

  scope :angular, -> { where(subtitle: 'Angular').order(created_at: :desc) }
  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails').order(created_at: :desc) }

  #after_initialize :set_defaults

  private

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.order('position ASC')
  end

  def angular
    @portfolio_items = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id]);
    @portfolio.destroy
    respond_to do |format|
      format.html{ redirect_to portfolios_path, notice: 'Portfolio was removed'}
      format.json{ head :no_content }
    end
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :thumb_image,
                                      :main_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |message| %>
      <%= js add_gritter(message, title: "Portfolio", sticky: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :thumb_image %>
  </div>

  <div class="form-group">
      <%= f.file_field :main_image %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <h2>Technologies used:</h2>
  <%= f.fields_for :technologies do |t| %>
    <%= render 'technology_fields', f: t %>
  <% end %>
  <div>
    <%= link_to_add_association 'Add Technology', f, :technologies %>
  </div>


  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Items</h1>
<%= link_to 'Create New Item', new_portfolio_path %>

<% @portfolio_items.each do |item| %>
  <p><%= link_to item.title, portfolio_path(item) %></p>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <%= image_tag item.thumb_image if item.thumb_image.present? %>
  <%= link_to 'Edit', edit_portfolio_path(item) %>
  <%= link_to 'Delete Portfolio',item, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/portfolios/edit.html.erb
<div class='container'>
  <h1>Edit new Portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <!-- <%= link_to 'Create New Item', new_portfolio_path %> -->
    <div class="row <%= 'sortable' if logged_in?(:site_admin) %>">
      <% @portfolio_items.each do |item| %>

        <div class="card" data-id="<%= item.id %>">
          <%= link_to (image_tag item.thumb_image), item     if item.thumb_image.present? %>
          <p class="card-text">
            <span><%= item.title %></span>
            <%= item.subtitle %>
          </p>
          <% if logged_in?(:site_admin) %>
            <%= link_to 'Edit', edit_portfolio_path(item) %>
            <%= link_to 'Delete Portfolio',item, method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end%>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class='container'>
      <h1>Create new Portfolio</h1>
      <%= render 'form', portfolio_item: @portfolio %>
</div>

app/views/portfolios/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-7'>
      <%= image_tag @portfolio.main_image, width: '100%' %>
    </div>
    <div class='col-md-5'>
      <h3><%= @portfolio.title %></h3>
      <hr>
      <p><%= @portfolio.subtitle %></p>
      <p><%= @portfolio.body %></p>

      <h2>Technologies Used:</h2>

      <% @portfolio.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>