config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'
  resources :portfolios do
    put :sort, on: :collection
  end
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about',   to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'

  mount ActionCable.server => '/cable'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Portfolio") %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Portfolio") %>
<% else flash[:notice] %>
  <%= js add_gritter(flash[:notice], title: "Portfolio") %>
<% end %>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Jordan Hudgens</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_musthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <%= link_to 'New Blog', new_blog_path  if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li><%= fa_icon "facebook"%></li>
      <li><%= fa_icon "github"%></li>
      <li><%= fa_icon "twitter"%></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <%= nav_helper '', 'div' %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <a href="#" class="btn btn-primary">Main call to action</a>
      <a href="#" class="btn btn-secondary">Secondary action</a>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Album</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>